"""Optional AI draft extraction adapter.

When AI_EXTRACTION_ENABLED=true, provides an interface for
AI-assisted claim/rule draft extraction from normalized text.
AI output is ALWAYS a draft — it can never auto-publish.
Human review is mandatory before any AI-generated content
becomes active.

When AI_EXTRACTION_ENABLED=false (default), all methods
raise AiExtractionDisabled.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Any, Protocol

from wb_ingestion.errors import IngestionProblemCode, IngestionError


def is_ai_enabled() -> bool:
    """Check if AI extraction is enabled via environment variable."""
    return os.environ.get("AI_EXTRACTION_ENABLED", "false").lower() == "true"


class AiExtractionDisabled(IngestionError):
    """Raised when AI extraction is attempted but disabled."""

    def __init__(self) -> None:
        super().__init__(
            IngestionProblemCode.AI_EXTRACTION_DISABLED,
            "AI extraction is disabled (AI_EXTRACTION_ENABLED != true)",
        )


@dataclass(frozen=True)
class DraftClaim:
    """A claim draft generated by AI. Always requires human review."""

    text: str
    evidence_excerpt: str
    source_url: str
    confidence: str = "draft"  # always draft
    requires_human_review: bool = True  # always True, cannot be overridden


@dataclass(frozen=True)
class DraftRule:
    """A rule draft generated by AI. Always requires human review."""

    rule_type: str  # eligibility, requirement, timing
    predicate: dict[str, Any]
    action: str
    claim_refs: list[str] = field(default_factory=list)
    requires_human_review: bool = True


@dataclass(frozen=True)
class ExtractionResult:
    """Result of AI draft extraction."""

    snapshot_id: str
    draft_claims: list[DraftClaim] = field(default_factory=list)
    draft_rules: list[DraftRule] = field(default_factory=list)
    model_version: str = ""
    extraction_metadata: dict[str, str] = field(default_factory=dict)


class AiExtractor(Protocol):
    """Protocol for AI extraction backends.

    Implementations must never auto-publish. They return drafts
    that require human review before becoming active.
    """

    def extract_claims(
        self, normalized_text: str, source_url: str
    ) -> list[DraftClaim]: ...

    def extract_rules(
        self, normalized_text: str, claims: list[DraftClaim]
    ) -> list[DraftRule]: ...


class NoOpExtractor:
    """Extractor used when AI is disabled. Returns empty results."""

    def extract_claims(
        self, normalized_text: str, source_url: str
    ) -> list[DraftClaim]:
        return []

    def extract_rules(
        self, normalized_text: str, claims: list[DraftClaim]
    ) -> list[DraftRule]:
        return []


def get_extractor() -> AiExtractor:
    """Get the configured AI extractor.

    Returns NoOpExtractor if AI_EXTRACTION_ENABLED is not true.
    """
    if not is_ai_enabled():
        return NoOpExtractor()

    # In the future, return a real extractor here
    # For now, even when enabled, return NoOp until an adapter is configured
    return NoOpExtractor()


def extract_draft(
    snapshot_id: str,
    normalized_text: str,
    source_url: str,
) -> ExtractionResult:
    """Run AI draft extraction on a snapshot.

    This is the main entry point. It:
    1. Checks if AI is enabled
    2. Runs extraction via the configured adapter
    3. Returns drafts (never publishes)

    Raises AiExtractionDisabled if AI is not enabled.
    """
    if not is_ai_enabled():
        raise AiExtractionDisabled()

    extractor = get_extractor()
    claims = extractor.extract_claims(normalized_text, source_url)
    rules = extractor.extract_rules(normalized_text, claims)

    return ExtractionResult(
        snapshot_id=snapshot_id,
        draft_claims=claims,
        draft_rules=rules,
    )
