create index if not exists idx_sources_next_check on content.sources(next_check_at) where status = 'active';
create index if not exists idx_snapshots_source_captured on content.source_snapshots(source_id, captured_at desc);
create index if not exists idx_claims_review on content.source_claims(status, review_due_at, hard_expiry_at);
create index if not exists idx_claims_territory on content.source_claims using gin(territory_ids);
create index if not exists idx_rules_event_dates on content.rule_revisions(event_type_id, effective_from, effective_to) where status in ('approved','active','stale');
create index if not exists idx_rules_jurisdictions on content.rule_revisions using gin(jurisdiction_ids);
create index if not exists idx_rules_claims on content.rule_revisions using gin(source_claim_ids);
create index if not exists idx_ruleset_members_rule on content.rule_set_members(rule_revision_id);
create index if not exists idx_gaps_open on content.research_gaps(status, next_review_at) where status <> 'resolved';
create index if not exists idx_cases_user_status on app.cases(user_id, status, updated_at desc) where deleted_at is null;
create index if not exists idx_cases_install_status on app.cases(installation_id, status, updated_at desc) where deleted_at is null;
create index if not exists idx_journeys_case_revision on app.journeys(case_id, revision desc);
create index if not exists idx_steps_journey_sequence on app.journey_steps(journey_id, sequence);
create index if not exists idx_requirements_step_status on app.journey_requirements(journey_step_id, status);
create index if not exists idx_documents_user_expiry on app.documents(user_id, expires_on) where deleted_at is null;
create index if not exists idx_notifications_due on app.notifications(status, due_at) where status = 'scheduled';
create index if not exists idx_feedback_open on app.feedback_reports(status, created_at) where status <> 'resolved';
create index if not exists idx_jobs_ready on app.jobs(priority, run_at, id) where status in ('queued','retry_wait');
create index if not exists idx_audit_entity on audit.events(entity_type, entity_id, occurred_at desc);
create index if not exists idx_audit_actor on audit.events(actor_type, actor_id, occurred_at desc);
